server:
  port: ${PORT:8081}
spring:
  application:
    name: orders

  ## Database Configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/orders}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:mysql}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

## Logging Configuration
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.jpa: DEBUG

## Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: orders

## Microservices Configuration
catalog:
  url: ${CATALOG_URL:http://catalog/api/v1}
